//
// Created by Richard Harman on 2. 10. 2022.
//

#ifndef IFJ_PROJECT_2022_SCANNER_H
#define IFJ_PROJECT_2022_SCANNER_H

typedef enum {
    Start,
    S_EOF,
    S_Dot,
    S_Left_Bracket,
    S_Right_Bracket,
    S_Left_Curly_Bracket,
    S_Right_Curly_Bracket,
    S_Semicolon,
    S_Plus,
    S_Comma,
    S_Multiply,
    S_Minus,
    S_Question_Mark,
    S_Number,
    S_Exponent_0,
    S_Exponent_1,
    S_Decimal_0,
    S_Decimal_1,
    S_Divide,
    S_Comment,
    S_Dollar,
    S_Var,
    S_Exclamation,
    S_Not_Equal_0,
    S_Not_Equal_1,
    S_Assign,
    S_Equal_0,
    S_Equal_1,
    S_Identifier,
    S_Greater,
    S_Greater_Equal,
    S_Less,
    S_Less_Equal,
    S_String_0,
    S_String_1,
    S_Escape_0,
    S_Escape_1,
    S_Octal_0,
    S_Octal_1,
    S_Octal_2,
    S_Hex_0,
    S_Hex_1,
    S_Hex_2,
    S_PHP_0,
    S_PHP_1,
    S_PHP_2,
    S_PHP_3,
    S_PHP_4,
    S_PHP_5,
    S_PHP_6,
    S_PHP_7,
    S_PHP_8,
    S_PHP_9,
    S_PHP_10,
    S_PHP_11,
    S_PHP_12,
    S_PHP_13,
    S_PHP_14,
    S_PHP_15,
    S_PHP_16,
    S_PHP_17,
    S_PHP_18,
    S_PHP_19,
    S_PHP_20,
    S_PHP_21,
    S_PHP_22,
    S_PHP_23,
    S_PHP_24,
    S_PHP_25,
    S_PHP_26,
    S_PHP_27,
    S_PHP_28,
    S_PHP_END,
    ERROR
} AutomatStates;

typedef struct {
    enum {
        VAR_ID,
        IDENTIFIER,
        STRING,
        EOF_T,
        LEFT_BRACKET,
        RIGHT_BRACKET,
        LEFT_CURLY_BRACKET,
        RIGHT_CURLY_BRACKET,
        SEMICOLON,
        PLUS,
        MINUS,
        COMMA,
        MULTIPLY,
        DOT,
        QUESTION_MARK,
        DIVIDE,
        NUMBER,
        DECIMAL_NUMBER,
        EXPONENT_NUMBER,
        GREATER,
        LESS,
        ASSIGN,
        EQUAL,
        NOT_EQUAL,
        COMMENT,
        PHP_DECLARE,
        ERROR_T,
    } type;
    union {
        char* string;
        int value;
        int index;
    };
} Token;

#endif //IFJ_PROJECT_2022_SCANNER_H
